version: '3'

services:
  postgres:
    container_name: earthquakes-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: